#!/bin/bash
usage () { echo "Pour avoir un peu d’aide si besoin

"; }

cpt=0
while getopts hd1:2:3: options
do
case $options in
1 ) echo $OPTARG > /tmp/rep1 ; cpt=$(($cpt + 1)) ;;
2 ) echo $OPTARG > /tmp/rep2 ; cpt=$(($cpt + 1)) ;;
3 ) echo $OPTARG > /tmp/rep3 ; cpt=$(($cpt + 1)) ;;
4 ) echo $OPTARG > /tmp/rep4 ; cpt=$(($cpt + 1)) ;;
5 ) echo $OPTARG > /tmp/rep5 ; cpt=$(($cpt + 1)) ;;
6 ) echo $OPTARG > /tmp/rep6 ; cpt=$(($cpt + 1)) ;;
7 ) echo $OPTARG > /tmp/rep7 ; cpt=$(($cpt + 1)) ;;
8 ) echo $OPTARG > /tmp/rep8 ; cpt=$(($cpt + 1)) ;;
9 ) echo $OPTARG > /tmp/rep9 ; cpt=$(($cpt + 1)) ;;
d ) delete="true" ;;
h  ) usage; exit;;
:  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
\? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
*  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
esac
done
shift $(( $OPTIND -1 ))

if [[ $# == 0 && $cpt == 0 ]] ; then echo "vous semblez n’avoir rien répondu!" ; usage; exit ;fi

num=1
for rep in $@ 
do
echo $rep > /tmp/rep${num}
num=$(($num + 1))
done

