#!/bin/bash
usage () { echo "Pour répondre aux questions utilisez cette syntaxe:

rep ma_reponse

rep ma_reponseàlaquestion1 ma_reponseàlaquestion2 ma_reponseàlaquestion3 ....

rep -1 ma_reponseàlaquestion1

rep -2 ma_reponseàlaquestion2

rep -2 ma_reponseàlaquestion2 ma_reponseàlaquestion1

rep -2 ma_reponseàlaquestion2_non_prise_en_compte ma_reponseàlaquestion1 ma_reponseàlaquestion2

rep -2 ma_reponseàlaquestion2 -3 ma_reponseàlaquestion3 -1 ma_reponseàlaquestion1

Si il y  a pluseurs réponse pour une question séparez-les par un tiret - 

Exemples: 

rep repA-repB-repE

ou : rep -1 repA-repB-repE


Attention respectez l’ordre, ne faites pas (cela compte faux):

rep repB-repA-repE


"; }

cpt=0
while getopts hd1:2:3: options
do
case $options in
1 ) echo $OPTARG > /tmp/rep1 ; cpt=$(($cpt + 1)) ;;
2 ) echo $OPTARG > /tmp/rep2 ; cpt=$(($cpt + 1)) ;;
3 ) echo $OPTARG > /tmp/rep3 ; cpt=$(($cpt + 1)) ;;
4 ) echo $OPTARG > /tmp/rep4 ; cpt=$(($cpt + 1)) ;;
5 ) echo $OPTARG > /tmp/rep5 ; cpt=$(($cpt + 1)) ;;
6 ) echo $OPTARG > /tmp/rep6 ; cpt=$(($cpt + 1)) ;;
7 ) echo $OPTARG > /tmp/rep7 ; cpt=$(($cpt + 1)) ;;
8 ) echo $OPTARG > /tmp/rep8 ; cpt=$(($cpt + 1)) ;;
9 ) echo $OPTARG > /tmp/rep9 ; cpt=$(($cpt + 1)) ;;
d ) delete="true" ;;
h  ) usage; exit;;
:  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
\? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
*  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
esac
done
shift $(( $OPTIND -1 ))

if [[ $# == 0 && $cpt == 0 ]] ; then echo "vous semblez n’avoir rien répondu!" ; usage; exit ;fi

num=1
for rep in $@ 
do
echo $rep > /tmp/rep${num}
num=$(($num + 1))
done

